[workspace]
resolver = "2"

members = [
    "coordinator",
    "cli",
    "utils",
    "service",
    "worker",
    "wasm",
    "bindings",
]

[workspace.dependencies]
tokio = { version = "1.20", features = ["full"] }
anyhow = { version = "1", features = ["backtrace"] }
thiserror = "1"
tokio-serde = { version = "0.9.0", features = ["json"] }
tokio-util = { version = "0.7.3", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.108"
futures = "0.3.21"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime.git", features = ["async"] }
wasmtime-wasi = { git = "https://github.com/bytecodealliance/wasmtime.git" }
wasi-common = { git = "https://github.com/bytecodealliance/wasmtime.git" }
wiggle = { git = "https://github.com/bytecodealliance/wasmtime.git" }
num-rational = { version = "0.4", features = ["serde"]}
borsh = { version = "1.3", features = ["unstable__schema", "derive"] }
bytes = "1.5"
