[package]
name = "worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lunatic = "0.14"
serde = "1"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
serde_json = "1"
thiserror = "1"
utils = { path = "../utils", features = ["lunatic"] }
anyhow = "1"
byteorder = "1.4"
lunatic-message-request = { path = "../lunatic-message-request"}
service = { path = "../service", features = ["lunatic"] }

[depdendencies.service]
features = ["lunatic"]
