[package]
name = "worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
serde_json = "1"
thiserror = "1"
utils = { path = "../utils" }
anyhow = "1"
byteorder = "1.4"
service = { path = "../service" }
tokio = { version = "1.20", features = ["full"] }
tokio-serde = { version = "0.8.0", features = ["json"] }
tokio-util = { version = "0.7.3", features = ["full"] }
futures = "0.3.21"
